// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PoorMansTSqlFormatterCmdLine {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralLanguageContent {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralLanguageContent() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PoorMansTSqlFormatterCmdLine.GeneralLanguageContent", typeof(GeneralLanguageContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PossiblePartialWriteWarningMessage {
            get {
                return ResourceManager.GetString("PossiblePartialWriteWarningMessage", resourceCulture);
            }
        }
        
        internal static string ParseErrorWarningPrefix {
            get {
                return ResourceManager.GetString("ParseErrorWarningPrefix", resourceCulture);
            }
        }
        
        internal static string UnrecognizedLanguageErrorMessage {
            get {
                return ResourceManager.GetString("UnrecognizedLanguageErrorMessage", resourceCulture);
            }
        }
        
        internal static string NoInputErrorMessage {
            get {
                return ResourceManager.GetString("NoInputErrorMessage", resourceCulture);
            }
        }
        
        internal static string ContentWriteFailureWarningMessage {
            get {
                return ResourceManager.GetString("ContentWriteFailureWarningMessage", resourceCulture);
            }
        }
        
        internal static string ProgramSummary {
            get {
                return ResourceManager.GetString("ProgramSummary", resourceCulture);
            }
        }
        
        internal static string BackupFailureWarningMessage {
            get {
                return ResourceManager.GetString("BackupFailureWarningMessage", resourceCulture);
            }
        }
        
        internal static string PathPatternErrorMessage {
            get {
                return ResourceManager.GetString("PathPatternErrorMessage", resourceCulture);
            }
        }
        
        internal static string ProgramUsageNotes {
            get {
                return ResourceManager.GetString("ProgramUsageNotes", resourceCulture);
            }
        }
        
        internal static string ParsingErrorWarningMessage {
            get {
                return ResourceManager.GetString("ParsingErrorWarningMessage", resourceCulture);
            }
        }
        
        internal static string UnrecognizedArgumentsErrorMessage {
            get {
                return ResourceManager.GetString("UnrecognizedArgumentsErrorMessage", resourceCulture);
            }
        }
        
        internal static string OutputFileCreationErrorMessage {
            get {
                return ResourceManager.GetString("OutputFileCreationErrorMessage", resourceCulture);
            }
        }
        
        internal static string FolderCreationFailureWarningMessage {
            get {
                return ResourceManager.GetString("FolderCreationFailureWarningMessage", resourceCulture);
            }
        }
        
        internal static string ErrorDetailMessageFragment {
            get {
                return ResourceManager.GetString("ErrorDetailMessageFragment", resourceCulture);
            }
        }
        
        internal static string FileReadFailureWarningMessage {
            get {
                return ResourceManager.GetString("FileReadFailureWarningMessage", resourceCulture);
            }
        }
        
        internal static string NoFilesFoundWarningMessage {
            get {
                return ResourceManager.GetString("NoFilesFoundWarningMessage", resourceCulture);
            }
        }
    }
}
